site_name: OctoFlex Docs
site_description: Documentación oficial del proyecto OctoFlex 🚀
nav:
  - Home: index.md
  - Documentación técnica: 
    - Ceph: docu_tecnica/ceph/ceph_base.md
    - Openstack: docu_tecnica/openstack/openstack_base.md
  - Blog: 
    - blog/index.md
  - Acerca de: about.md
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'es'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - attr_list
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

plugins: 
  - search
  - social
  - minify
  - blog: 
      authors_file: "blog/authors/.authors.yml"
