site_name: OctoFlex Docs
site_description: Documentación oficial del proyecto OctoFlex 🚀
nav:
  - Home: index.md
  - Documentación técnica: 
    - Ceph: docu_tecnica/ceph/ceph_base.md
    - Openstack: docu_tecnica/openstack/openstack_base.md
    
  - Acerca de: about.md
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'es'
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - attr_list
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

plugins: 
  - search
  - social
